### ISSUE TITLE
Updating to a newer engine

### ISSUE THREAD

**Issue by VeryHolyCheeeese** [TheDiG3/TwitchPlay#7]
Building is pain please do it for us also add UE5 support.
I have emailed you and also can you please fix the documentation, the documentation requires permissions to view which none of us have.

**Comment by TheDiG3** [comment]
Unfortunately I don't have enough time to work on this anymore. Sorry for that :(
Documentation: [TwitchPlayGuide.pdf](https://github.com/TheDiG3/TwitchPlay/files/7219281/TwitchPlayGuide.pdf)

**Comment by VeryHolyCheeeese** [comment]
I understand, i do need this for a project. Is there really no time for updating it?

**Comment by TheDiG3** [comment]
I'm sorry but unfortunately I don't have the time for it :(
